### ISSUE TITLE
ReferenceError: dialog is not defined

### ISSUE THREAD

**Issue by williamesp2015** [siara-cc/sqlite3_page_explorer#2]
I copied files in my URL but when click on "Open Database" on the website or on Windows  I get error:   ReferenceError: dialog is not defined
I need to Add /remove and display database on my website

**Comment by siara-cc** [comment]
I am not sure how you are invoking it.  Perhaps you are trying to open index.html from the browser?  But it is an Electron application and should be invoked using Electron. It cannot be installed in a website.  To run it, please install electron on your desktop using `npm install electron -g` and use `npm start` after cloning this repo and making it current folder.

Also this is not a general purpose utility for manipulating SQLite databases.  This app is used to show the internal structure of the database - how and where records are stored.
